services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: gucci
      POSTGRES_USER: gucci
      POSTGRES_PASSWORD: gucci
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8097:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gucci
      SPRING_DATASOURCE_USERNAME: gucci
      SPRING_DATASOURCE_PASSWORD: gucci
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JAVA_TOOL_OPTIONS: "-Duser.timezone=Europe/Moscow"
      LOG_DIR: /logs
      LOGGING_LEVEL_COM_CHAPEULLAH_GUCCIGOBLIN: DEBUG

      COC_API_TOKEN: ${COC_API_TOKEN}
      COC_CLAN_TAG: ${COC_CLAN_TAG}
      COC_API_BASE_URL: ${COC_API_BASE_URL}

      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}

    tty: true
    stdin_open: true
    volumes:
      - applogs:/logs

volumes:
  pgdata:
  applogs: