coc:
  apiToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImI4NDdmMTQ0LTU0ZDUtNDg4Mi04NzQyLTVlYjM3MzU1YWQ2NSIsImlhdCI6MTc5MDQyMTg3Nywic3ViIjoiZGV2ZWxvcGVyLzM1OTUxZThhLWU0ZmMtNTJkNi1jYjY2LTQwMjM0MjMyNmRkZiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE4Ni4yNDYuNTEuMjUxIl0sInR5cGUiOiJjbGllbnQifV19.R_uyPIktddk3Zw8vJwIUF3of1YHjXcNpZ0PStzixAkogN-QB92xrDw05QiTWl0FeVEJiWie1cPx1QAf6KB5Mdw
  clanTag: '#2C020L9P0'
spring:
  application:
    name: gucci-goblin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
  main:
    web-application-type: none