coc:
  apiToken: ${COC_API_TOKEN}
  clanTag: '#2C020L9P0'

telegram:
  bot:
    apiToken: ${TELEGRAM_BOT_TOKEN}

spring:
  task:
    scheduling:
      pool:
        size: 2
  application:
    name: gucci-goblin

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'

  main:
    web-application-type: none