coc:
  apiToken: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjY5Y2M4OTM5LTVjZDUtNGIxNy1iOWY0LWMxNzBlYjYwYTUxMSIsImlhdCI6MTc5MDQwMTY2MSwic3ViIjoiZGV2ZWxvcGVyLzM1OTUxZThhLWU0ZmMtNTJkNi1jYjY2LTQwMjM0MjMyNmRkZiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE4OS43NC4xMjEuMTgzIl0sInR5cGUiOiJjbGllbnQifV19.IjRUrTkdRKNTC08ift8EPVGcJvRLqeb8nrPtA1rcPqfMWN1JqkGxv8M38Njg0RNPY5AoGjgcrE5CM-RVda4NPQ
  clanTag: '#2C020L9P0'
spring:
  application:
    name: gucci-goblin
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: 'true'
  main:
    web-application-type: none