spring.application.name=gucci-goblin

spring.main.web-application-type=none

coc.apiToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImM1NmM3YmJlLTQzNzAtNDdiNy05M2YzLWRjMWU1MjBlNjBkZiIsImlhdCI6MTc3MDU1NDk1OSwic3ViIjoiZGV2ZWxvcGVyLzM1OTUxZThhLWU0ZmMtNTJkNi1jYjY2LTQwMjM0MjMyNmRkZiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE5My4xMjQuMTEyLjEwMiJdLCJ0eXBlIjoiY2xpZW50In1dfQ.rP9EUdMbR-9XeDIhfIzOg9M4YmOtH66YWKVVW2l8cbYJwN6xXljYMJUsbNj4gBfPO6y0ycMKhquy1dity89RtA
coc.clanTag=#2C020L9P0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.shell.interactive.enabled = true
spring.shell.command.quit.enabled=false

spring.output.ansi.enabled=ALWAYS