spring.application.name=GucciGoblin

spring.main.web-application-type=none

coc.apiToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjZkYzM1MTEyLTZlYmYtNDQ0Yy04MTg5LWU1Y2QxMzY2M2JiYSIsImlhdCI6MTc3MjI0ODYxNywic3ViIjoiZGV2ZWxvcGVyLzM1OTUxZThhLWU0ZmMtNTJkNi1jYjY2LTQwMjM0MjMyNmRkZiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE3Ni45OS4xOTkuMTUiXSwidHlwZSI6ImNsaWVudCJ9XX0._l-B5iF7rTHPFWqIcw__YQ48FdCmlEQvR4ZzElFG78EHZZrRj-OByTJt30rRFe53ZvimHA7PeaeKVe8iJCGIiA
coc.clanTag=#2C020L9P0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.shell.interactive.enabled = true
spring.shell.command.quit.enabled=false

spring.output.ansi.enabled=ALWAYS