spring.application.name=GucciGoblin

spring.main.web-application-type=none

coc.apiToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjJiZWFmZTUzLTQ3OGMtNDcwOS05ZTQyLTgyN2RiZWQwMDE4ZCIsImlhdCI6MTc3MTkwMjgzOSwic3ViIjoiZGV2ZWxvcGVyLzM1OTUxZThhLWU0ZmMtNTJkNi1jYjY2LTQwMjM0MjMyNmRkZiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjE3Ni45OS4yNTUuMjE1Il0sInR5cGUiOiJjbGllbnQifV19.Qe2VYM4Hx_A9_C0V0KlhvkDVq2bPwrmfU0MCSmZkhbGLuqDExPz75phRuNEsWe-LkWO_Yo-86HNViqvMAAO1bA
coc.clanTag=#2C020L9P0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
